import { z } from "zod";
export declare const applicationCreateSchema: z.ZodObject<{
    tenantId: z.ZodString;
    createdBy: z.ZodString;
    jobId: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    company: z.ZodString;
    position: z.ZodString;
    source: z.ZodOptional<z.ZodEnum<["LinkedIn", "Indeed", "Stepstone", "Xing", "Glassdoor", "Monster", "Company Website", "Referral", "Gmail", "Manual", "Other"]>>;
    applicationStatus: z.ZodDefault<z.ZodEnum<["Drafted", "Ready", "In Progress", "Applied", "Follow-Up Due", "Replied", "Interview", "Offer", "Rejected", "Archived"]>>;
    responseStatus: z.ZodDefault<z.ZodEnum<["No Response", "Positive Reply", "Negative Reply", "Auto Reply", "Needs Review"]>>;
    followUpStatus: z.ZodDefault<z.ZodEnum<["Not Needed", "Scheduled", "Due Today", "Overdue", "Sent"]>>;
    jobUrl: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    contactEmail: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    dateApplied: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
}, "strip", z.ZodTypeAny, {
    position: string;
    tenantId: string;
    createdBy: string;
    company: string;
    applicationStatus: "Applied" | "Interview" | "Offer" | "Rejected" | "Archived" | "Ready" | "Drafted" | "In Progress" | "Follow-Up Due" | "Replied";
    responseStatus: "No Response" | "Positive Reply" | "Negative Reply" | "Auto Reply" | "Needs Review";
    followUpStatus: "Not Needed" | "Scheduled" | "Due Today" | "Overdue" | "Sent";
    source?: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website" | undefined;
    jobUrl?: string | undefined;
    dateApplied?: string | undefined;
    contactEmail?: string | undefined;
    notes?: string | undefined;
    jobId?: string | undefined;
}, {
    position: string;
    tenantId: string;
    createdBy: string;
    company: string;
    source?: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website" | undefined;
    jobUrl?: unknown;
    dateApplied?: unknown;
    contactEmail?: string | undefined;
    notes?: string | undefined;
    jobId?: unknown;
    applicationStatus?: "Applied" | "Interview" | "Offer" | "Rejected" | "Archived" | "Ready" | "Drafted" | "In Progress" | "Follow-Up Due" | "Replied" | undefined;
    responseStatus?: "No Response" | "Positive Reply" | "Negative Reply" | "Auto Reply" | "Needs Review" | undefined;
    followUpStatus?: "Not Needed" | "Scheduled" | "Due Today" | "Overdue" | "Sent" | undefined;
}>;
export declare const applicationUpdateSchema: z.ZodObject<{
    tenantId: z.ZodOptional<z.ZodString>;
    createdBy: z.ZodOptional<z.ZodString>;
    jobId: z.ZodOptional<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>;
    company: z.ZodOptional<z.ZodString>;
    position: z.ZodOptional<z.ZodString>;
    source: z.ZodOptional<z.ZodOptional<z.ZodEnum<["LinkedIn", "Indeed", "Stepstone", "Xing", "Glassdoor", "Monster", "Company Website", "Referral", "Gmail", "Manual", "Other"]>>>;
    applicationStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<["Drafted", "Ready", "In Progress", "Applied", "Follow-Up Due", "Replied", "Interview", "Offer", "Rejected", "Archived"]>>>;
    responseStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<["No Response", "Positive Reply", "Negative Reply", "Auto Reply", "Needs Review"]>>>;
    followUpStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<["Not Needed", "Scheduled", "Due Today", "Overdue", "Sent"]>>>;
    jobUrl: z.ZodOptional<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>;
    contactEmail: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dateApplied: z.ZodOptional<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>;
}, "strip", z.ZodTypeAny, {
    position?: string | undefined;
    source?: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website" | undefined;
    tenantId?: string | undefined;
    createdBy?: string | undefined;
    company?: string | undefined;
    jobUrl?: string | undefined;
    dateApplied?: string | undefined;
    contactEmail?: string | undefined;
    notes?: string | undefined;
    jobId?: string | undefined;
    applicationStatus?: "Applied" | "Interview" | "Offer" | "Rejected" | "Archived" | "Ready" | "Drafted" | "In Progress" | "Follow-Up Due" | "Replied" | undefined;
    responseStatus?: "No Response" | "Positive Reply" | "Negative Reply" | "Auto Reply" | "Needs Review" | undefined;
    followUpStatus?: "Not Needed" | "Scheduled" | "Due Today" | "Overdue" | "Sent" | undefined;
}, {
    position?: string | undefined;
    source?: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website" | undefined;
    tenantId?: string | undefined;
    createdBy?: string | undefined;
    company?: string | undefined;
    jobUrl?: unknown;
    dateApplied?: unknown;
    contactEmail?: string | undefined;
    notes?: string | undefined;
    jobId?: unknown;
    applicationStatus?: "Applied" | "Interview" | "Offer" | "Rejected" | "Archived" | "Ready" | "Drafted" | "In Progress" | "Follow-Up Due" | "Replied" | undefined;
    responseStatus?: "No Response" | "Positive Reply" | "Negative Reply" | "Auto Reply" | "Needs Review" | undefined;
    followUpStatus?: "Not Needed" | "Scheduled" | "Due Today" | "Overdue" | "Sent" | undefined;
}>;
