import { z } from "zod";
export declare const documentCreateSchema: z.ZodObject<{
    tenantId: z.ZodString;
    createdBy: z.ZodString;
    fileName: z.ZodString;
    type: z.ZodEnum<["CV", "Cover Letter", "Research", "Portfolio", "Other", "cv_resume", "cover_letter_template", "supporting_document", "ai_draft", "pdf_export"]>;
    status: z.ZodDefault<z.ZodEnum<["Draft", "Ready", "Sent", "Archived"]>>;
    jobId: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    applicationId: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>;
    contentText: z.ZodOptional<z.ZodString>;
    documentKind: z.ZodOptional<z.ZodEnum<["Research", "Cover Letter", "CV", "PDF Export", "Other"]>>;
    storageProvider: z.ZodOptional<z.ZodString>;
    storagePath: z.ZodOptional<z.ZodString>;
    storageLocation: z.ZodOptional<z.ZodString>;
    storageUrl: z.ZodOptional<z.ZodString>;
    driveFileId: z.ZodOptional<z.ZodString>;
    driveFileLink: z.ZodOptional<z.ZodString>;
    googleDriveFileId: z.ZodOptional<z.ZodString>;
    googleDriveFolderId: z.ZodOptional<z.ZodString>;
    profileDocumentType: z.ZodOptional<z.ZodEnum<["cv_resume", "cover_letter_template", "supporting_document"]>>;
    isActiveProfileDocument: z.ZodOptional<z.ZodBoolean>;
    sourceFileName: z.ZodOptional<z.ZodString>;
    extractionStatus: z.ZodOptional<z.ZodEnum<["Provided", "Failed", "Not Required"]>>;
    extractionError: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    type: "Research" | "Other" | "CV" | "Cover Letter" | "Portfolio" | "cv_resume" | "cover_letter_template" | "supporting_document" | "ai_draft" | "pdf_export";
    status: "Archived" | "Ready" | "Sent" | "Draft";
    tenantId: string;
    createdBy: string;
    fileName: string;
    metadata?: Record<string, unknown> | undefined;
    applicationId?: string | undefined;
    notes?: string | undefined;
    jobId?: string | undefined;
    documentKind?: "Research" | "Other" | "CV" | "Cover Letter" | "PDF Export" | undefined;
    contentText?: string | undefined;
    storageProvider?: string | undefined;
    storagePath?: string | undefined;
    storageLocation?: string | undefined;
    storageUrl?: string | undefined;
    driveFileId?: string | undefined;
    driveFileLink?: string | undefined;
    googleDriveFileId?: string | undefined;
    googleDriveFolderId?: string | undefined;
    profileDocumentType?: "cv_resume" | "cover_letter_template" | "supporting_document" | undefined;
    isActiveProfileDocument?: boolean | undefined;
    sourceFileName?: string | undefined;
    extractionStatus?: "Failed" | "Provided" | "Not Required" | undefined;
    extractionError?: string | undefined;
}, {
    type: "Research" | "Other" | "CV" | "Cover Letter" | "Portfolio" | "cv_resume" | "cover_letter_template" | "supporting_document" | "ai_draft" | "pdf_export";
    tenantId: string;
    createdBy: string;
    fileName: string;
    status?: "Archived" | "Ready" | "Sent" | "Draft" | undefined;
    metadata?: Record<string, unknown> | undefined;
    applicationId?: string | undefined;
    notes?: string | undefined;
    jobId?: string | undefined;
    documentKind?: "Research" | "Other" | "CV" | "Cover Letter" | "PDF Export" | undefined;
    contentText?: string | undefined;
    storageProvider?: string | undefined;
    storagePath?: string | undefined;
    storageLocation?: string | undefined;
    storageUrl?: string | undefined;
    driveFileId?: string | undefined;
    driveFileLink?: string | undefined;
    googleDriveFileId?: string | undefined;
    googleDriveFolderId?: string | undefined;
    profileDocumentType?: "cv_resume" | "cover_letter_template" | "supporting_document" | undefined;
    isActiveProfileDocument?: boolean | undefined;
    sourceFileName?: string | undefined;
    extractionStatus?: "Failed" | "Provided" | "Not Required" | undefined;
    extractionError?: string | undefined;
}>;
export declare const documentUpdateSchema: z.ZodObject<{
    tenantId: z.ZodOptional<z.ZodString>;
    createdBy: z.ZodOptional<z.ZodString>;
    fileName: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodEnum<["CV", "Cover Letter", "Research", "Portfolio", "Other", "cv_resume", "cover_letter_template", "supporting_document", "ai_draft", "pdf_export"]>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["Draft", "Ready", "Sent", "Archived"]>>>;
    jobId: z.ZodOptional<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>>;
    applicationId: z.ZodOptional<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>>;
    contentText: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    documentKind: z.ZodOptional<z.ZodOptional<z.ZodEnum<["Research", "Cover Letter", "CV", "PDF Export", "Other"]>>>;
    storageProvider: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    storagePath: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    storageLocation: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    storageUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    driveFileId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    driveFileLink: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    googleDriveFileId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    googleDriveFolderId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    profileDocumentType: z.ZodOptional<z.ZodOptional<z.ZodEnum<["cv_resume", "cover_letter_template", "supporting_document"]>>>;
    isActiveProfileDocument: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    sourceFileName: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    extractionStatus: z.ZodOptional<z.ZodOptional<z.ZodEnum<["Provided", "Failed", "Not Required"]>>>;
    extractionError: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    metadata: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
}, "strip", z.ZodTypeAny, {
    type?: "Research" | "Other" | "CV" | "Cover Letter" | "Portfolio" | "cv_resume" | "cover_letter_template" | "supporting_document" | "ai_draft" | "pdf_export" | undefined;
    status?: "Archived" | "Ready" | "Sent" | "Draft" | undefined;
    tenantId?: string | undefined;
    createdBy?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
    applicationId?: string | undefined;
    notes?: string | undefined;
    jobId?: string | undefined;
    fileName?: string | undefined;
    documentKind?: "Research" | "Other" | "CV" | "Cover Letter" | "PDF Export" | undefined;
    contentText?: string | undefined;
    storageProvider?: string | undefined;
    storagePath?: string | undefined;
    storageLocation?: string | undefined;
    storageUrl?: string | undefined;
    driveFileId?: string | undefined;
    driveFileLink?: string | undefined;
    googleDriveFileId?: string | undefined;
    googleDriveFolderId?: string | undefined;
    profileDocumentType?: "cv_resume" | "cover_letter_template" | "supporting_document" | undefined;
    isActiveProfileDocument?: boolean | undefined;
    sourceFileName?: string | undefined;
    extractionStatus?: "Failed" | "Provided" | "Not Required" | undefined;
    extractionError?: string | undefined;
}, {
    type?: "Research" | "Other" | "CV" | "Cover Letter" | "Portfolio" | "cv_resume" | "cover_letter_template" | "supporting_document" | "ai_draft" | "pdf_export" | undefined;
    status?: "Archived" | "Ready" | "Sent" | "Draft" | undefined;
    tenantId?: string | undefined;
    createdBy?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
    applicationId?: string | undefined;
    notes?: string | undefined;
    jobId?: string | undefined;
    fileName?: string | undefined;
    documentKind?: "Research" | "Other" | "CV" | "Cover Letter" | "PDF Export" | undefined;
    contentText?: string | undefined;
    storageProvider?: string | undefined;
    storagePath?: string | undefined;
    storageLocation?: string | undefined;
    storageUrl?: string | undefined;
    driveFileId?: string | undefined;
    driveFileLink?: string | undefined;
    googleDriveFileId?: string | undefined;
    googleDriveFolderId?: string | undefined;
    profileDocumentType?: "cv_resume" | "cover_letter_template" | "supporting_document" | undefined;
    isActiveProfileDocument?: boolean | undefined;
    sourceFileName?: string | undefined;
    extractionStatus?: "Failed" | "Provided" | "Not Required" | undefined;
    extractionError?: string | undefined;
}>;
