import { z } from "zod";
export declare const jobCreateSchema: z.ZodObject<{
    tenantId: z.ZodString;
    createdBy: z.ZodString;
    company: z.ZodString;
    position: z.ZodString;
    title: z.ZodOptional<z.ZodString>;
    source: z.ZodDefault<z.ZodEnum<["LinkedIn", "Indeed", "Stepstone", "Xing", "Glassdoor", "Monster", "Company Website", "Referral", "Gmail", "Manual", "Other"]>>;
    status: z.ZodDefault<z.ZodEnum<["New", "Research", "Drafting", "Ready to Apply", "Applied", "Interview", "Offer", "Rejected", "Archived"]>>;
    priority: z.ZodDefault<z.ZodEnum<["Low", "Medium", "High", "Urgent"]>>;
    location: z.ZodOptional<z.ZodString>;
    jobUrl: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    salaryRange: z.ZodOptional<z.ZodString>;
    deadline: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    description: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "New" | "Research" | "Drafting" | "Ready to Apply" | "Applied" | "Interview" | "Offer" | "Rejected" | "Archived";
    position: string;
    source: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website";
    tenantId: string;
    createdBy: string;
    company: string;
    priority: "Low" | "Medium" | "High" | "Urgent";
    description?: string | undefined;
    location?: string | undefined;
    jobUrl?: string | undefined;
    salaryRange?: string | undefined;
    deadline?: string | undefined;
    title?: string | undefined;
}, {
    position: string;
    tenantId: string;
    createdBy: string;
    company: string;
    status?: "New" | "Research" | "Drafting" | "Ready to Apply" | "Applied" | "Interview" | "Offer" | "Rejected" | "Archived" | undefined;
    description?: string | undefined;
    source?: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website" | undefined;
    priority?: "Low" | "Medium" | "High" | "Urgent" | undefined;
    location?: string | undefined;
    jobUrl?: unknown;
    salaryRange?: string | undefined;
    deadline?: unknown;
    title?: string | undefined;
}>;
export declare const jobUpdateSchema: z.ZodObject<{
    tenantId: z.ZodOptional<z.ZodString>;
    createdBy: z.ZodOptional<z.ZodString>;
    company: z.ZodOptional<z.ZodString>;
    position: z.ZodOptional<z.ZodString>;
    title: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    source: z.ZodOptional<z.ZodDefault<z.ZodEnum<["LinkedIn", "Indeed", "Stepstone", "Xing", "Glassdoor", "Monster", "Company Website", "Referral", "Gmail", "Manual", "Other"]>>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["New", "Research", "Drafting", "Ready to Apply", "Applied", "Interview", "Offer", "Rejected", "Archived"]>>>;
    priority: z.ZodOptional<z.ZodDefault<z.ZodEnum<["Low", "Medium", "High", "Urgent"]>>>;
    location: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    jobUrl: z.ZodOptional<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>;
    salaryRange: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    deadline: z.ZodOptional<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    status?: "New" | "Research" | "Drafting" | "Ready to Apply" | "Applied" | "Interview" | "Offer" | "Rejected" | "Archived" | undefined;
    description?: string | undefined;
    position?: string | undefined;
    source?: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website" | undefined;
    tenantId?: string | undefined;
    createdBy?: string | undefined;
    company?: string | undefined;
    priority?: "Low" | "Medium" | "High" | "Urgent" | undefined;
    location?: string | undefined;
    jobUrl?: string | undefined;
    salaryRange?: string | undefined;
    deadline?: string | undefined;
    title?: string | undefined;
}, {
    status?: "New" | "Research" | "Drafting" | "Ready to Apply" | "Applied" | "Interview" | "Offer" | "Rejected" | "Archived" | undefined;
    description?: string | undefined;
    position?: string | undefined;
    source?: "Referral" | "Other" | "Manual" | "Gmail" | "LinkedIn" | "Indeed" | "Stepstone" | "Xing" | "Glassdoor" | "Monster" | "Company Website" | undefined;
    tenantId?: string | undefined;
    createdBy?: string | undefined;
    company?: string | undefined;
    priority?: "Low" | "Medium" | "High" | "Urgent" | undefined;
    location?: string | undefined;
    jobUrl?: unknown;
    salaryRange?: string | undefined;
    deadline?: unknown;
    title?: string | undefined;
}>;
