"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.integrationTestStatuses = exports.REPORT_PERIOD_TYPES = exports.REPORT_DELIVERY_STATUSES = exports.reportPeriodTypes = exports.reportDeliveryStatuses = exports.reportTypes = exports.reportStatuses = exports.automationModuleKeys = exports.automationCategories = exports.automationStatuses = exports.PDF_EXPORT_STATUSES = exports.CALENDAR_EVENT_STATUSES = exports.DOCUMENT_ROUTING_STATUSES = exports.FOLDER_PROVISION_STATUSES = exports.pdfExportStatuses = exports.calendarEventStatuses = exports.documentRoutingStatuses = exports.folderProvisionStatuses = exports.EMAIL_REPLY_CLASSIFICATIONS = exports.APPLICATION_WORKFLOW_STATUSES = exports.emailReplyClassifications = exports.applicationWorkflowStatuses = exports.DOCUMENT_GENERATION_STATUSES = exports.AI_PROCESSING_STATUSES = exports.AI_RUN_TYPES = exports.documentGenerationStatuses = exports.aiProcessingStatuses = exports.aiRunTypes = exports.documentTypes = exports.documentStatuses = exports.prepStatuses = exports.interviewStatuses = exports.interviewTypes = exports.contactRelationships = exports.followUpStatuses = exports.responseStatuses = exports.duplicateStatuses = exports.applicationStatuses = exports.jobStatuses = exports.userStatuses = exports.tenantStatuses = void 0;
exports.tenantStatuses = ["Active", "Trialing", "Past Due", "Suspended", "Cancelled"];
exports.userStatuses = ["Active", "Invited", "Suspended", "Removed"];
exports.jobStatuses = ["New", "Research", "Drafting", "Ready to Apply", "Applied", "Interview", "Offer", "Rejected", "Archived"];
exports.applicationStatuses = ["Drafted", "Ready", "In Progress", "Applied", "Follow-Up Due", "Replied", "Interview", "Offer", "Rejected", "Archived"];
exports.duplicateStatuses = ["Unique", "Possible Duplicate", "Duplicate", "Skipped"];
exports.responseStatuses = ["No Response", "Positive Reply", "Negative Reply", "Auto Reply", "Needs Review"];
exports.followUpStatuses = ["Not Needed", "Scheduled", "Due Today", "Overdue", "Sent"];
exports.contactRelationships = ["Recruiter", "Hiring Manager", "Referral", "Employee", "Networking", "Other"];
exports.interviewTypes = ["Recruiter Screen", "Technical", "Behavioral", "Hiring Manager", "Panel", "Final Round", "Offer Discussion"];
exports.interviewStatuses = ["Scheduled", "Awaiting Confirmation", "Rescheduled", "Completed", "Cancelled", "No Show"];
exports.prepStatuses = ["Not Started", "In Progress", "Ready", "Overdue"];
exports.documentStatuses = ["Draft", "Ready", "Sent", "Archived"];
exports.documentTypes = ["CV", "Cover Letter", "Research", "Portfolio", "Other", "cv_resume", "cover_letter_template", "supporting_document", "ai_draft", "pdf_export"];
exports.aiRunTypes = ["job-extraction", "research-generation", "draft-generation", "reply-classification"];
exports.aiProcessingStatuses = ["Not Started", "Queued", "Processing", "Completed", "Failed"];
exports.documentGenerationStatuses = ["Pending", "Generated", "Failed", "Needs Review"];
exports.AI_RUN_TYPES = exports.aiRunTypes;
exports.AI_PROCESSING_STATUSES = exports.aiProcessingStatuses;
exports.DOCUMENT_GENERATION_STATUSES = exports.documentGenerationStatuses;
exports.applicationWorkflowStatuses = ["Not Started", "Queued", "Completed", "Failed"];
exports.emailReplyClassifications = ["Positive Reply", "Negative Reply", "Auto Reply", "Interview Intent", "Offer Intent", "Needs Review", "No Response"];
exports.APPLICATION_WORKFLOW_STATUSES = exports.applicationWorkflowStatuses;
exports.EMAIL_REPLY_CLASSIFICATIONS = exports.emailReplyClassifications;
exports.folderProvisionStatuses = ["Not Started", "Queued", "Completed", "Failed"];
exports.documentRoutingStatuses = ["Not Started", "Queued", "Completed", "Failed"];
exports.calendarEventStatuses = ["Not Created", "Queued", "Created", "Failed"];
exports.pdfExportStatuses = ["Not Started", "Queued", "Exported", "Failed"];
exports.FOLDER_PROVISION_STATUSES = exports.folderProvisionStatuses;
exports.DOCUMENT_ROUTING_STATUSES = exports.documentRoutingStatuses;
exports.CALENDAR_EVENT_STATUSES = exports.calendarEventStatuses;
exports.PDF_EXPORT_STATUSES = exports.pdfExportStatuses;
exports.automationStatuses = ["Success", "Warning", "Failed", "Running", "Healthy", "Paused", "Error"];
exports.automationCategories = ["Jobs", "Applications", "Contacts", "Interviews", "Documents", "Reports", "System"];
exports.automationModuleKeys = ["job-intake", "duplicate-protection", "folder-automation", "applied-status", "interview-scheduling", "cv-routing", "email-reply-detection", "follow-up-reminder", "pdf-export", "research-document", "ai-processing", "network-follow-up", "offer-tracking", "deadline-alert", "lifecycle-monitoring", "daily-digest", "weekly-report"];
exports.reportStatuses = ["Sent", "Generated", "Failed", "Scheduled"];
exports.reportTypes = ["Daily Digest", "Weekly Performance", "PDF Export", "Manual Report"];
exports.reportDeliveryStatuses = ["Not Sent", "Queued", "Sent", "Failed"];
exports.reportPeriodTypes = ["daily", "weekly", "manual"];
exports.REPORT_DELIVERY_STATUSES = exports.reportDeliveryStatuses;
exports.REPORT_PERIOD_TYPES = exports.reportPeriodTypes;
/** Result of integration connectivity test (stubbed). */
exports.integrationTestStatuses = ["Success", "Failed", "Warning"];
