export declare const tenantStatuses: readonly ["Active", "Trialing", "Past Due", "Suspended", "Cancelled"];
export declare const userStatuses: readonly ["Active", "Invited", "Suspended", "Removed"];
export declare const jobStatuses: readonly ["New", "Research", "Drafting", "Ready to Apply", "Applied", "Interview", "Offer", "Rejected", "Archived"];
export declare const applicationStatuses: readonly ["Drafted", "Ready", "In Progress", "Applied", "Follow-Up Due", "Replied", "Interview", "Offer", "Rejected", "Archived"];
export declare const duplicateStatuses: readonly ["Unique", "Possible Duplicate", "Duplicate", "Skipped"];
export declare const responseStatuses: readonly ["No Response", "Positive Reply", "Negative Reply", "Auto Reply", "Needs Review"];
export declare const followUpStatuses: readonly ["Not Needed", "Scheduled", "Due Today", "Overdue", "Sent"];
export declare const contactRelationships: readonly ["Recruiter", "Hiring Manager", "Referral", "Employee", "Networking", "Other"];
export declare const interviewTypes: readonly ["Recruiter Screen", "Technical", "Behavioral", "Hiring Manager", "Panel", "Final Round", "Offer Discussion"];
export declare const interviewStatuses: readonly ["Scheduled", "Awaiting Confirmation", "Rescheduled", "Completed", "Cancelled", "No Show"];
export declare const prepStatuses: readonly ["Not Started", "In Progress", "Ready", "Overdue"];
export declare const documentStatuses: readonly ["Draft", "Ready", "Sent", "Archived"];
export declare const documentTypes: readonly ["CV", "Cover Letter", "Research", "Portfolio", "Other", "cv_resume", "cover_letter_template", "supporting_document", "ai_draft", "pdf_export"];
export declare const aiRunTypes: readonly ["job-extraction", "research-generation", "draft-generation", "reply-classification"];
export declare const aiProcessingStatuses: readonly ["Not Started", "Queued", "Processing", "Completed", "Failed"];
export declare const documentGenerationStatuses: readonly ["Pending", "Generated", "Failed", "Needs Review"];
export declare const AI_RUN_TYPES: readonly ["job-extraction", "research-generation", "draft-generation", "reply-classification"];
export declare const AI_PROCESSING_STATUSES: readonly ["Not Started", "Queued", "Processing", "Completed", "Failed"];
export declare const DOCUMENT_GENERATION_STATUSES: readonly ["Pending", "Generated", "Failed", "Needs Review"];
export declare const applicationWorkflowStatuses: readonly ["Not Started", "Queued", "Completed", "Failed"];
export declare const emailReplyClassifications: readonly ["Positive Reply", "Negative Reply", "Auto Reply", "Interview Intent", "Offer Intent", "Needs Review", "No Response"];
export declare const APPLICATION_WORKFLOW_STATUSES: readonly ["Not Started", "Queued", "Completed", "Failed"];
export declare const EMAIL_REPLY_CLASSIFICATIONS: readonly ["Positive Reply", "Negative Reply", "Auto Reply", "Interview Intent", "Offer Intent", "Needs Review", "No Response"];
export declare const folderProvisionStatuses: readonly ["Not Started", "Queued", "Completed", "Failed"];
export declare const documentRoutingStatuses: readonly ["Not Started", "Queued", "Completed", "Failed"];
export declare const calendarEventStatuses: readonly ["Not Created", "Queued", "Created", "Failed"];
export declare const pdfExportStatuses: readonly ["Not Started", "Queued", "Exported", "Failed"];
export declare const FOLDER_PROVISION_STATUSES: readonly ["Not Started", "Queued", "Completed", "Failed"];
export declare const DOCUMENT_ROUTING_STATUSES: readonly ["Not Started", "Queued", "Completed", "Failed"];
export declare const CALENDAR_EVENT_STATUSES: readonly ["Not Created", "Queued", "Created", "Failed"];
export declare const PDF_EXPORT_STATUSES: readonly ["Not Started", "Queued", "Exported", "Failed"];
export declare const automationStatuses: readonly ["Success", "Warning", "Failed", "Running", "Healthy", "Paused", "Error"];
export declare const automationCategories: readonly ["Jobs", "Applications", "Contacts", "Interviews", "Documents", "Reports", "System"];
export declare const automationModuleKeys: readonly ["job-intake", "duplicate-protection", "folder-automation", "applied-status", "interview-scheduling", "cv-routing", "email-reply-detection", "follow-up-reminder", "pdf-export", "research-document", "ai-processing", "network-follow-up", "offer-tracking", "deadline-alert", "lifecycle-monitoring", "daily-digest", "weekly-report"];
export declare const reportStatuses: readonly ["Sent", "Generated", "Failed", "Scheduled"];
export declare const reportTypes: readonly ["Daily Digest", "Weekly Performance", "PDF Export", "Manual Report"];
export declare const reportDeliveryStatuses: readonly ["Not Sent", "Queued", "Sent", "Failed"];
export declare const reportPeriodTypes: readonly ["daily", "weekly", "manual"];
export declare const REPORT_DELIVERY_STATUSES: readonly ["Not Sent", "Queued", "Sent", "Failed"];
export declare const REPORT_PERIOD_TYPES: readonly ["daily", "weekly", "manual"];
/** Result of integration connectivity test (stubbed). */
export declare const integrationTestStatuses: readonly ["Success", "Failed", "Warning"];
export type IntegrationTestStatus = (typeof integrationTestStatuses)[number];
