import { Router } from "express";
import { authMiddleware } from "../middleware/auth.middleware";
import { tenantMiddleware } from "../middleware/tenant.middleware";
import { applicationRoutes } from "./application.routes";
import { authProtectedRoutes } from "./auth.protected.routes";
import { authPublicRoutes } from "./auth.public.routes";
import { aiRoutes } from "./ai.routes";
import { adminRoutes } from "./admin.routes";
import { automationRoutes } from "./automation.routes";
import { billingRoutes } from "./billing.routes";
import { billingWebhookRoutes } from "./billing.webhook.routes";
import { contactRoutes } from "./contact.routes";
import { demoRoutes } from "./demo.routes";
import { documentRoutes } from "./document.routes";
import { healthRoutes } from "./health.routes";
import { googleOAuthProtectedRouter, googleOAuthPublicRouter } from "./google-oauth.routes";
import { integrationRoutes } from "./integration.routes";
import { interviewRoutes } from "./interview.routes";
import { notificationRoutes } from "./notification.routes";
import { jobIntakeRoutes } from "./job-intake.routes";
import { jobRoutes } from "./job.routes";
import { reportRoutes } from "./report.routes";
import { systemRoutes } from "./system.routes";
import { todayRoutes } from "./today.routes";
import { tenantRoutes } from "./tenant.routes";
import { agentPublicRoutes, agentProtectedRoutes } from "./agent.routes";

export const apiRoutes = Router();

apiRoutes.use(healthRoutes);
apiRoutes.use("/api", healthRoutes);
apiRoutes.use("/auth", authPublicRoutes);
apiRoutes.use("/agent", agentPublicRoutes);
apiRoutes.use("/agent", agentProtectedRoutes);
apiRoutes.use("/billing", billingWebhookRoutes);
apiRoutes.use("/integrations/google", googleOAuthPublicRouter);
apiRoutes.use(authMiddleware);
apiRoutes.use(tenantMiddleware);
apiRoutes.use("/auth", authProtectedRoutes);
apiRoutes.use("/billing", billingRoutes);
apiRoutes.use("/tenants", tenantRoutes);
apiRoutes.use(jobIntakeRoutes);
apiRoutes.use("/jobs", jobRoutes);
apiRoutes.use("/today", todayRoutes);
apiRoutes.use("/applications", applicationRoutes);
apiRoutes.use("/interviews", interviewRoutes);
apiRoutes.use("/documents", documentRoutes);
apiRoutes.use("/notifications", notificationRoutes);
apiRoutes.use("/reports", reportRoutes);
apiRoutes.use("/automation", automationRoutes);
apiRoutes.use("/ai", aiRoutes);
apiRoutes.use("/admin", adminRoutes);
apiRoutes.use("/integrations", integrationRoutes);
apiRoutes.use("/integrations/google", googleOAuthProtectedRouter);
apiRoutes.use(systemRoutes);
apiRoutes.use(demoRoutes);
